### ISSUE TITLE
DevOps | Quickstart: Create a CI/CD pipeline for .NET with Azure DevOps Projects

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#10]
* Tracking: #5
* Docs: [Create a CI/CD pipeline for .NET with Azure DevOps Starter](https://docs.microsoft.com/en-us/azure/devops-project/azure-devops-project-aspnet-core?WT.mc_id=osscontributhon-event-juyoo)
* Issue: 
* PR:

**Comment by johypark** [comment]
@justinyoo Please assign @seonyounggg who already works with this docs(ko-kr).

**Comment by seonyounggg** [comment]
PR : [#1116](https://github.com/MicrosoftDocs/azure-docs.ko-kr/pull/1116)
(Merged)

**Comment by seonyounggg** [comment]
Merged!
