### ISSUE TITLE
Runtime install doc | Modify Linux build installation doc

### ISSUE THREAD

**Issue by KimKiHyuk** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#16]
Tracking: #3
* Issue:  dotnet/runtime#40573
* PR: dotnet/runtime#40576

**Comment by KimKiHyuk** [comment]
tag : runtime, doc
**Done**

멘토님 프로젝트 태그 부탁드립니다! 태그되면 이슈 클로즈 하겠습니다.

@justinyoo

**Comment by justinyoo** [comment]
@KimKiHyuk 프로젝트 칸반 보드에서도 DONE 쪽으로 옮기면 좋을 것 같아요! 이게 자동으로 안 움직이네 ㄷㄷㄷ

**Comment by justinyoo** [comment]
아... 저기서 DONE 으로 하면 자동으로 클로징 되는 거였나...?

**Comment by KimKiHyuk** [comment]
> 아... 저기서 DONE 으로 하면 자동으로 클로징 되는 거였나...?

음.. 대시보드에서는 제가 권한이 없어서 이동이 안되네용
