### ISSUE TITLE
Runtime Test  | Help get System.Text.Json test coverage to 100% (or close to it)

### ISSUE THREAD

**Issue by KimKiHyuk** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#17]
Tracking: #3
Issue: dotnet/runtime#32341

## Work in progress / Done
끝난 항목에 대해서 체크
- [ ] JsonDocument 
- [x] JsonHelper

assign : @hiMinju  @wooooooood

**Comment by KimKiHyuk** [comment]
tag : runtime, 
team : adadaDot

**WIP**

@justinyoo

**Comment by KimKiHyuk** [comment]
~~throwHelper/ThrowArgumentException_InvalidUTF8 해당 함수에 대한 테스트케이스를 작성중입니다.~~
~~JsonHelpers 테스트케이스 작성중    **끝**~~

**Comment by wooooooood** [comment]
System.Text.Json.JsonDocument 저는 이걸로 하겠습니다~

**Comment by hiMinju** [comment]
System.Text.Json.Serialization.Converters.IListConverter`1
이 부분 보니까 if문 안에 들어가도록 고쳐주면 될것 같아서 한번 해보겠습니다!
