### ISSUE TITLE
.NET Core 이슈

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#3]
아래 링크는 닷넷 코어 관련 이슈들 모음입니다. 쭉 한번 둘러 보시고, 하나씩 pick 해 보세욤.

[https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs)

**Comment by KimKiHyuk** [comment]
~~## 김기혁 진행중인 이슈~~

~~- [ ] https://github.com/dotnet/runtime/issues/36007 Include filename in load exception (#36007)~~
~~- [x] https://github.com/dotnet/runtime/issues/30457 (PR : https://github.com/dotnet/runtime/pull/40477) **(merged)**~~
~~- [x] https://github.com/dotnet/runtime/issues/40573 (PR : https://github.com/dotnet/runtime/pull/40576) **(merged)**~~
~~- [x] https://github.com/dotnet/runtime/pull/40600 **(merged)**~~

**Comment by hongman** [comment]
coronet 팀이 보고 있는 이슈입니다.
https://github.com/dotnet/runtime/issues/32760

**Comment by justinyoo** [comment]
#14

**Comment by wooooooood** [comment]
#13

**Comment by KimKiHyuk** [comment]
#15

**Comment by KimKiHyuk** [comment]
https://github.com/devrel-kr/oss-contributhon-2020-dotnetcore-sdk/issues/16

**Comment by KimKiHyuk** [comment]
#17
