### ISSUE TITLE
Tutorial | Create a .NET Core console application

### ISSUE THREAD

**Issue by johypark** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#32]
## Introduction

Tracking: [Learn .NET Core and the .NET Core SDK tools by exploring these tutorials](https://docs.microsoft.com/en-us/dotnet/core/tutorials/)

## Docs
[Tutorial: Create a .NET Core console application using Visual Studio](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio)
[Tutorial: Create a .NET Core console application using Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
[Tutorial: Create a .NET Core console application using Visual Studio for Mac](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac)

## Pull requests (en-us only)

- [x] dotnet/docs#20236

- [x] dotnet/docs#20240 (suggested changes)

- [x] dotnet/docs#20253

- [x] dotnet/docs#20269

**Comment by johypark** [comment]
Improve ko-kr docs
Docs: [자습서: Visual Studio를 사용하여 .NET Core 콘솔 애플리케이션 만들기](https://docs.microsoft.com/ko-kr/dotnet/core/tutorials/with-visual-studio)
PR: https://github.com/dotnet/docs.ko-kr/pull/245

**Comment by johypark** [comment]
Enhance docs
Docs: https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio
PR: https://github.com/dotnet/docs/pull/20236

**Comment by johypark** [comment]
Prevent possible over-localization(suggested changes)
Docs: https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio
PR: https://github.com/dotnet/docs/pull/20240

**Comment by johypark** [comment]
Enhance docs
Docs: https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac, https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code
PR: https://github.com/dotnet/docs/pull/20252

**Comment by JohyPark** [comment]
Rebase
PR: https://github.com/dotnet/docs/pull/20253
> Enhance docs
> Docs: https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac, https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code
> PR: [dotnet/docs#20252](https://github.com/dotnet/docs/pull/20252)

**Comment by JohyPark** [comment]
Merged

> Enhance docs
> Docs: https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac, https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code
> PR: [dotnet/docs#20252](https://github.com/dotnet/docs/pull/20252)

**Comment by johypark** [comment]
Rebase
PR: https://github.com/dotnet/docs/pull/20253
> Enhance docs
> Docs: https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac, https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code
> PR: [dotnet/docs#20252](https://github.com/dotnet/docs/pull/20252)

**Comment by JohyPark** [comment]
Merged
> Rebase
> PR: [dotnet/docs#20253](https://github.com/dotnet/docs/pull/20253)
> 
> > Enhance docs
> > Docs: https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac, https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code
> > PR: [dotnet/docs#20252](https://github.com/dotnet/docs/pull/20252)

**Comment by johypark** [comment]
Update other docs name
PR: dotnet/docs#20269

**Comment by JohyPark** [comment]
Merged
> Update other docs name
> PR: [dotnet/docs#20269](https://github.com/dotnet/docs/pull/20269)

**Comment by JohyPark** [comment]
Improve debugging-with-visual-studio series
PR: dotnet/docs#20294
