### ISSUE TITLE
Azure SDK for .NET 이슈

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#4]
아래 링크는 애저 SDK 관련 이슈들 문서입니다. 쭉 한번 둘러 보시고, 하나씩 pick 해 보세욤.

[https://github.com/azure/azure-sdk-for-net/issues?q=is%3Aissue+is%3Aopen+label%3A%22Up+for+grabs%22](https://github.com/azure/azure-sdk-for-net/issues?q=is%3Aissue+is%3Aopen+label%3A%22Up+for+grabs%22)

**Comment by hongman** [comment]
coronet 팀이 보고 있는 issue 입니다.
https://github.com/Azure/azure-sdk-for-net/issues/11763

**Comment by soo-toance** [comment]
sprinter팀이 보고 있는 issue입니다.
[[Track One Event Hubs Tests] Randomize partition picked #7178](https://github.com/Azure/azure-sdk-for-net/issues/7178)
