### ISSUE TITLE
Apache Spark | Increase Spark.Worker.UnitTest test coverage for different Spark versions

### ISSUE THREAD

**Issue by KimKiHyuk** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#42]
PR: https://github.com/dotnet/spark/pull/638
status  : **merged**
assign : @KimKiHyuk 
team : adadaDot

**Comment by wooooooood** [comment]
크.. 멋지십니다 👍👍👍

**Comment by KimKiHyuk** [comment]
> 크.. 멋지십니다 👍👍👍

본업때문에 바쁘실텐데 오픈소스도 참여하시는 게 더 멋있으십니다!  👍  마지막까지 화이팅!
