### ISSUE TITLE
애저 Getting Started 문서

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#5]
아래 링크는 애저 Getting Started 문서들입니다. 카테고리별로 정리해 놨는데, 이것 말고도 더 많지만 우선 이정도만 해도 충분할 것 같아요.

| 번호 | 카테고리 | 제목 |
| --- | --- | --- |
| 1 | Active Directory | [Add sign-in with Microsoft to ASP.NET Core web apps - Microsoft identity platform](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp?WT.mc_id=osscontributhon-event-juyoo) |
| 2 | Active Directory | [Add Microsoft identity platform sign-in to an ASP.NET web app](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-v2-aspnet-webapp?WT.mc_id=osscontributhon-event-juyoo) |
| 3 | Active Directory | [Build an Azure AD .NET web API for authentication & authorization](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-v1-dotnet-webapi?WT.mc_id=osscontributhon-event-juyoo) |
| 4 | Active Directory | [Add sign-in with Microsoft to an ASP.NET web app](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-v1-aspnet-webapp?WT.mc_id=osscontributhon-event-juyoo) |
| 5 | Active Directory | [Quickstart: Set up sign-in for an ASP.NET web app - Azure AD B2C](https://docs.microsoft.com/ko-kr/azure/active-directory-b2c/quickstart-web-app-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 6 | Active Directory | [Call a ASP.NET Web API protected by Microsoft identity platform](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-v2-dotnet-native-aspnet?WT.mc_id=osscontributhon-event-juyoo) |
| 7 | Active Directory | [Sign in users & call Microsoft Graph APIs from .NET Desktop (WPF)](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-v1-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 8 | Active Directory | [Acquire token & call Microsoft Graph (.NET Core Console) (v1.0)](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-v1-netcore-daemon?WT.mc_id=osscontributhon-event-juyoo) |
| 9 | App Configuration | [Quickstart for Azure App Configuration with ASP.NET Core](https://docs.microsoft.com/ko-kr/azure/azure-app-configuration/quickstart-aspnet-core-app?WT.mc_id=osscontributhon-event-juyoo) |
| 10 | App Configuration | [Quickstart for adding feature flags to ASP.NET Core](https://docs.microsoft.com/ko-kr/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core?WT.mc_id=osscontributhon-event-juyoo) |
| 11 | App Configuration | [Quickstart for Azure App Configuration with .NET Framework](https://docs.microsoft.com/ko-kr/azure/azure-app-configuration/quickstart-dotnet-app?WT.mc_id=osscontributhon-event-juyoo) |
| 12 | App Configuration | [Quickstart for Azure App Configuration with .NET Core](https://docs.microsoft.com/ko-kr/azure/azure-app-configuration/quickstart-dotnet-core-app?WT.mc_id=osscontributhon-event-juyoo) |
| 13 | App Configuration | [Quickstart for adding feature flags to .NET Framework apps](https://docs.microsoft.com/ko-kr/azure/azure-app-configuration/quickstart-feature-flag-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 14 | App Insights | [Quickstart ASP.NET Core - Azure Monitor Application Insights - Azure Monitor](https://docs.microsoft.com/ko-kr/azure/azure-monitor/learn/dotnetcore-quick-start?WT.mc_id=osscontributhon-event-juyoo) |
| 15 | App Insights | [Monitor your ASP.NET Web App  with Azure Application Insights - Azure Monitor](https://docs.microsoft.com/ko-kr/azure/azure-monitor/learn/quick-monitor-portal?WT.mc_id=osscontributhon-event-juyoo) |
| 16 | App Service | [QuickStart: Create a C# ASP.NET Core app - Azure App Service](https://docs.microsoft.com/ko-kr/azure/app-service/app-service-web-get-started-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 17 | App Service | [QuickStart: Create a C# ASP.NET app - Azure App Service](https://docs.microsoft.com/ko-kr/azure/app-service/app-service-web-get-started-dotnet-framework?WT.mc_id=osscontributhon-event-juyoo) |
| 18 | Azure Batch | [Azure Quickstart - Run Batch job - .NET - Azure Batch](https://docs.microsoft.com/ko-kr/azure/batch/quick-run-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 19 | Caching | [Quickstart: Use Azure Cache for Redis with .NET apps](https://docs.microsoft.com/ko-kr/azure/azure-cache-for-redis/cache-dotnet-how-to-use-azure-redis-cache?WT.mc_id=osscontributhon-event-juyoo) |
| 20 | Caching | [Create an ASP.NET web app with Azure Cache for Redis](https://docs.microsoft.com/ko-kr/azure/azure-cache-for-redis/cache-web-app-howto?WT.mc_id=osscontributhon-event-juyoo) |
| 21 | Caching | [Quickstart: Use Azure Cache for Redis with .NET Core apps](https://docs.microsoft.com/ko-kr/azure/azure-cache-for-redis/cache-dotnet-core-quickstart?WT.mc_id=osscontributhon-event-juyoo) |
| 22 | Cognitive Services | [Quickstart: Computer Vision client library for .NET - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/computer-vision/quickstarts-sdk/csharp-sdk?WT.mc_id=osscontributhon-event-juyoo) |
| 23 | Cognitive Services | [Quickstart: Create a search index in C# using .NET - Azure Cognitive Search](https://docs.microsoft.com/ko-kr/azure/search/search-get-started-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 24 | Cognitive Services | [Quickstart: Face client library for .NET - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/face/quickstarts/csharp-sdk?WT.mc_id=osscontributhon-event-juyoo) |
| 25 | Cognitive Services | [Quickstart: Form Recognizer client library for .NET - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/form-recognizer/quickstarts/dotnet-sdk?WT.mc_id=osscontributhon-event-juyoo) |
| 26 | Cognitive Services | [Quickstart: Detect anomalies in time series data using the Anomaly Detector client library for .NET - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/anomaly-detector/quickstarts/detect-data-anomalies-csharp-sdk?WT.mc_id=osscontributhon-event-juyoo) |
| 27 | Cognitive Services | [Quickstart: Content Moderator client library for .NET - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/content-moderator/dotnet-sdk-quickstart?WT.mc_id=osscontributhon-event-juyoo) |
| 28 | Cognitive Services | [Quickstart: Bing Autosuggest client library for .NET - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/bing-autosuggest/quickstarts/csharp-sdk?WT.mc_id=osscontributhon-event-juyoo) |
| 29 | Cognitive Services | [Quickstart: Language Understanding (LUIS) authoring client library 3.x for .NET - Azure Cognitive Services](https://docs.microsoft.com/ko-kr/azure/cognitive-services/luis/sdk-csharp-3x?WT.mc_id=osscontributhon-event-juyoo) |
| 30 | Cosmos DB | [Quickstart - Build a .NET console app to manage Azure Cosmos DB SQL API resources](https://docs.microsoft.com/ko-kr/azure/cosmos-db/create-sql-api-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 31 | Cosmos DB | [Manage Azure Cosmos DB SQL API resources using .Net V4 SDK](https://docs.microsoft.com/ko-kr/azure/cosmos-db/create-sql-api-dotnet-v4?WT.mc_id=osscontributhon-event-juyoo) |
| 32 | Cosmos DB | [Quickstart: Table API with .NET - Azure Cosmos DB](https://docs.microsoft.com/ko-kr/azure/cosmos-db/create-table-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 33 | Cosmos DB | [Build a web app using Azure Cosmos DB's API for MongoDB and .NET SDK](https://docs.microsoft.com/ko-kr/azure/cosmos-db/create-mongodb-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 34 | Cosmos DB | [Build an Azure Cosmos DB .NET Framework, Core application using the Gremlin API](https://docs.microsoft.com/ko-kr/azure/cosmos-db/create-graph-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 35 | Cosmos DB | [Quickstart: Cassandra API with .NET - Azure Cosmos DB](https://docs.microsoft.com/ko-kr/azure/cosmos-db/create-cassandra-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 36 | Cosmos DB | [Build a Xamarin app with .NET and Azure Cosmos DB's API for MongoDB](https://docs.microsoft.com/ko-kr/azure/cosmos-db/create-mongodb-xamarin?WT.mc_id=osscontributhon-event-juyoo) |
| 37 | Data Factory | [Create Azure data factory using .NET SDK - Azure Data Factory](https://docs.microsoft.com/ko-kr/azure/data-factory/quickstart-create-data-factory-dot-net?WT.mc_id=osscontributhon-event-juyoo) |
| 38 | DevOps | [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/ko-kr/azure/devops/pipelines/ecosystems/dotnet-core?WT.mc_id=osscontributhon-event-juyoo) |
| 39 | DevOps | [Build ASP.NET apps - Azure Pipelines](https://docs.microsoft.com/ko-kr/azure/devops/pipelines/apps/aspnet/build-aspnet-4?WT.mc_id=osscontributhon-event-juyoo) |
| 40 | DevOps | [Quickstart: Create a CI/CD pipeline for .NET with Azure DevOps Projects](https://docs.microsoft.com/ko-kr/azure/devops-project/azure-devops-project-aspnet-core?WT.mc_id=osscontributhon-event-juyoo) |
| 41 | DevOps | [Build your .NET desktop app for Windows - Azure Pipelines](https://docs.microsoft.com/ko-kr/azure/devops/pipelines/apps/windows/dot-net?WT.mc_id=osscontributhon-event-juyoo) |
| 42 | Event Hubs | [Azure Event Hubs - Send/receive events using the .NET Framework](https://docs.microsoft.com/ko-kr/azure/event-hubs/event-hubs-dotnet-framework-getstarted-send?WT.mc_id=osscontributhon-event-juyoo) |
| 43 | Event Hubs | [Send or receive events from Azure Event Hubs using .NET (latest)](https://docs.microsoft.com/ko-kr/azure/event-hubs/get-started-dotnet-standard-send-v2?WT.mc_id=osscontributhon-event-juyoo) |
| 44 | IoT  | [Control a device from Azure IoT Hub quickstart (.NET)](https://docs.microsoft.com/ko-kr/azure/iot-hub/quickstart-control-device-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 45 | Key Vault | [Quickstart -  Azure Key Vault client library for .NET (v4)](https://docs.microsoft.com/ko-kr/azure/key-vault/quick-create-net?WT.mc_id=osscontributhon-event-juyoo) |
| 46 | Key Vault | [Quickstart -  Azure Key Vault client library for .NET (SDK v3)](https://docs.microsoft.com/ko-kr/azure/key-vault/quick-create-net-v3?WT.mc_id=osscontributhon-event-juyoo) |
| 47 | Kubernetes (with Azure Dev Spaces) | [Debug and iterate on Kubernetes: Visual Studio Code & .NET Core - Azure Dev Spaces](https://docs.microsoft.com/ko-kr/azure/dev-spaces/quickstart-netcore?WT.mc_id=osscontributhon-event-juyoo) |
| 48 | Kubernetes (with Azure Dev Spaces) | [Debug and iterate on Kubernetes: Visual Studio & .NET Core - Azure Dev Spaces](https://docs.microsoft.com/ko-kr/azure/dev-spaces/quickstart-netcore-visualstudio?WT.mc_id=osscontributhon-event-juyoo) |
| 49 | Service Fabric | [Quickly create a .NET app on Service Fabric in Azure - Azure Service Fabric](https://docs.microsoft.com/ko-kr/azure/service-fabric/service-fabric-quickstart-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 50 | SignalR | [Develop with ASP.NET - Azure SignalR Service](https://docs.microsoft.com/ko-kr/azure/azure-signalr/signalr-quickstart-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 51 | SQL Database | [Use Visual Studio with .NET and C# to query - Azure SQL Database](https://docs.microsoft.com/ko-kr/azure/sql-database/sql-database-connect-query-dotnet-visual-studio?WT.mc_id=osscontributhon-event-juyoo) |
| 52 | SQL Database | [Use .NET Core to query - Azure SQL Database](https://docs.microsoft.com/ko-kr/azure/sql-database/sql-database-connect-query-dotnet-core?WT.mc_id=osscontributhon-event-juyoo) |
| 53 | Storage | [Quickstart: Azure Blob storage library v12 - .NET](https://docs.microsoft.com/ko-kr/azure/storage/blobs/storage-quickstart-blobs-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 54 | Storage | [Quickstart: Azure Blob storage client library for .NET](https://docs.microsoft.com/ko-kr/azure/storage/blobs/storage-quickstart-blobs-dotnet-legacy?WT.mc_id=osscontributhon-event-juyoo) |
| 55 | Storage | [Quickstart: Azure Queue storage library v12 - .NET](https://docs.microsoft.com/ko-kr/azure/storage/queues/storage-quickstart-queues-dotnet?WT.mc_id=osscontributhon-event-juyoo) |
| 56 | Storage | [Quickstart: Use Azure Storage v11 for .NET to manage a queue](https://docs.microsoft.com/ko-kr/azure/storage/queues/storage-quickstart-queues-dotnet-legacy?WT.mc_id=osscontributhon-event-juyoo) |
| 57 | WebApp for Containers | [Quickstart: Run a Linux ASP.NET Core app - Azure App Service](https://docs.microsoft.com/ko-kr/azure/app-service/containers/quickstart-dotnetcore?WT.mc_id=osscontributhon-event-juyoo) |
| 58 | DevOps | [Build ASP.NET apps - Azure Pipelines](https://docs.microsoft.com/ko-kr/azure/devops/pipelines/apps/aspnet/build-aspnet-4?WT.mc_id=osscontributhon-event-juyoo) |
| 59 | DevOps | [Quickstart: Create a CI/CD pipeline for .NET with Azure DevOps Projects](https://docs.microsoft.com/ko-kr/azure/devops-project/azure-devops-project-aspnet-core?WT.mc_id=osscontributhon-event-juyoo) |

**Comment by heesunlee9** [comment]
I am working on and [pulled a request](https://github.com/MicrosoftDocs/azure-docs/pull/60426)

**Comment by heesunlee9** [comment]
[team CDO]

I am reading and following 

43 | Event Hubs | Send or receive events from Azure Event Hubs using .NET (latest)

**Comment by heesunlee9** [comment]
I did one pull requested and it was [merged!](https://github.com/MicrosoftDocs/azure-docs/pull/60433) for the first time in my life.

**Comment by DaeunSim** [comment]
닷지팀에서는 Getting Started 문서에서 이슈를 선정하였습니다.

|카테고리|제목|담당자|
|----------|-----|-------|
|App Configuration|[Quickstart for adding feature flags to ASP.NET Core](https://docs.microsoft.com/ko-kr/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core?WT.mc_id=osscontributhon-event-juyoo)|@kim3278|
|App Service|[QuickStart: Create a C# ASP.NET Core app - Azure App Service](https://docs.microsoft.com/ko-kr/azure/app-service/app-service-web-get-started-dotnet?WT.mc_id=osscontributhon-event-juyoo)|@inclue|
|Unit Testing|[Unit testing C# with NUnit and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit)|@DaeunSim|

**Comment by johypark** [comment]
59 | DevOps | Quickstart: Create a CI/CD pipeline for .NET with Azure DevOps Projects

해당 문서를 확인 중에 있습니다.

**Comment by hiMinju** [comment]
멘토님께서 올려주신 문서는 아니지만 [#60438](https://github.com/MicrosoftDocs/azure-docs/issues/60438) 이슈를 확인하여 제가 대신 PR을 생성하였습니다.
결론적으로 [#60465](https://github.com/MicrosoftDocs/azure-docs/pull/60465) merged 되었습니다!

**Comment by seonyounggg** [comment]
@JohyPark 엇 혹시 번역본 수정하시는 거라면 제가 이미 해당 문서에 [PR](https://github.com/MicrosoftDocs/azure-docs.ko-kr/pull/1116) 보냈습니다ㅜㅜ

**Comment by johypark** [comment]
@seonyounggg 확인했습니다! 다른 문서 수정 예정입니다.

**Comment by hongman** [comment]
금주 coronet 팀이 담당 할 docs 문서들입니다. 매주 1인 1docs 수정 할 계획입니다.

카테고리 | 제목 | 담당자 | Pull Request | ko-kr
-- | -- | -- | -- | --
Active Directory | [Call a ASP.NET Web API protected by Microsoft identity platform](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/quickstart-v2-dotnet-native-aspnet?WT.mc_id=osscontributhon-event-juyoo) | @hongman | https://github.com/MicrosoftDocs/azure-docs/pull/60691 | https://github.com/MicrosoftDocs/azure-docs.ko-kr/pull/1120 |
DevOps | [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?WT.mc_id=osscontributhon-event-juyoo&view=azure-devops?WT.mc_id=osscontributhon-event-juyoo) | @JohyPark | https://github.com/MicrosoftDocs/azure-devops-docs/pull/9046 https://github.com/MicrosoftDocs/azure-devops-docs/pull/9054 
Key Vault | [Securely save secret application settings for a web application](https://docs.microsoft.com/ko-kr/azure/key-vault/general/vs-secure-secret-appsettings) | @MakerDev |

**Comment by heesunlee9** [comment]
CDO 팀의 이희선입니다. 

43 | Event Hubs | Send or receive events from Azure Event Hubs using .NET (latest)
은 따라해 보면서 검토 했습니다. 이상이 없었습니다. 
다만 단어 하나가 의미상으로 혼동될 수 있는게 있어서 PR 하나 올려놨습니다

[#60528](https://github.com/MicrosoftDocs/azure-docs/pull/60528)

**Comment by heesunlee9** [comment]
그리고 애저 Getting Started 문서 관련은 아닙니다만

문서 수정관련하여 PR 두 개 올렸고, merged 되었습니다.
 
[#19455](https://github.com/dotnet/AspNetCore.Docs/pull/19455)
[#19458](https://github.com/dotnet/AspNetCore.Docs/pull/19458)

**Comment by heesunlee9** [comment]
혹시 저나 다른 팀이나 검토 완료 된 부분이 있으면 여기 공유해 주시면 감사하겠습니다. 겹치지 않기 위해서 입니다. 
위 표의 문서에다가 취소선 긋는 것도 괜찮을 것 같습니다.

**Comment by soo-toance** [comment]
스프린터 팀은 아래 문서 담당해서 진행하기로 했습니다 : ) 

번호| 카테고리| 문서|담당자
-- | -- | --|--
41 | DevOps | [Build your .NET desktop app for Windows - Azure Pipelines](https://docs.microsoft.com/ko-kr/azure/devops/pipelines/apps/windows/dot-net?WT.mc_id=osscontributhon-event-juyoo&view=azure-devops&tabs=github)|@focusonmx
50 | SignalR | [Develop with ASP.NET - Azure SignalR Service](https://docs.microsoft.com/ko-kr/azure/azure-signalr/signalr-quickstart-dotnet?WT.mc_id=osscontributhon-event-juyoo)|@soo-toance
51 | SQL Database | [Use Visual Studio with .NET and C# to query - Azure SQL Database](https://docs.microsoft.com/ko-kr/azure/azure-sql/database/connect-query-dotnet-visual-studio?WT.mc_id=osscontributhon-event-juyoo)|@seonyounggg
52 | SQL Database | [Use .NET Core to query - Azure SQL Database](https://docs.microsoft.com/ko-kr/azure/azure-sql/database/connect-query-dotnet-core?WT.mc_id=osscontributhon-event-juyoo)|@seonyounggg

**Comment by wooooooood** [comment]
Getting started 문서는 아니지만 오타수정했습니다! #12

**Comment by hongman** [comment]
[Call a ASP.NET Web API protected by Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-dotnet-native-aspnet?WT.mc_id=osscontributhon-event-juyoo) 에 대한 문서를 수정했습니다.

스텝 수정 및 부가 설명 작성이 되었습니다.

https://github.com/MicrosoftDocs/azure-docs/pull/60691

merge되면 azure-docs -> azure-docs-ko-kr -> azure-samples 에 대한 나머지를 진행 할 예정입니다.

**Comment by DaeunSim** [comment]
[닷지팀] 금주에 검토할 문서입니다.

|카테고리|제목|
|----------|-----|
|SignalR|[Tutorial: Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio)|@DaeunSim|
