### ISSUE TITLE
Tutorial | Test a .NET Standard class library with .NET Core

### ISSUE THREAD

**Issue by johypark** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#53]
## Introduction

Tracking: [Learn .NET Core and the .NET Core SDK tools by exploring these tutorials](https://docs.microsoft.com/en-us/dotnet/core/tutorials/)

## Docs
[Tutorial: Test a .NET Standard class library with .NET Core using Visual Studio](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio)
[Tutorial: Test a .NET Standard class library with .NET Core using Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio-code)
[Tutorial: Test a .NET Standard class library with .NET Core using Visual Studio for Mac](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio-mac)

## Pull requests (en-us only)

- [x] dotnet/docs#20395

- [ ] dotnet/docs#20494

**Comment by johypark** [comment]
Update other docs name
dotnet/docs#20395

**Comment by johypark** [comment]
Improve minor syntax(closed)
dotnet/docs#20397

**Comment by JohyPark** [comment]
Add description of debugging test unit
https://github.com/dotnet/docs/pull/20494

**Comment by johypark** [comment]
Add description of debugging test unit
dotnet/docs#20494
