### ISSUE TITLE
App Configuration | Quickstart for adding feature flags to ASP.NET Core

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#7]
* Tracking: #5
* Docs: [Quickstart: Add feature flags to an ASP.NET Core app](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core?WT.mc_id=osscontributhon-event-juyoo&tabs=core3x)
* Issue:
* PR:

**Comment by kim3278** [comment]
- Docs: [Quickstart: Add feature flags to an ASP.NET Core app](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core?WT.mc_id=osscontributhon-event-juyoo&tabs=core3x)

- PR: https://github.com/MicrosoftDocs/azure-docs/pull/60698

**Comment by kim3278** [comment]
Merged!
