### ISSUE TITLE
App Service | Quickstart: Create an ASP.NET Core app with Azure App Configuration

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#8]
* Tracking: #5
* Docs: [Quickstart: Create an ASP.NET Core app with Azure App Configuration](https://docs.microsoft.com/azure/azure-app-configuration/quickstart-aspnet-core-app?tabs=core2x&WT.mc_id=osscontributhon-event-juyoo)
* Issue:
* PR:

**Comment by inclue** [comment]
위의 Docs가 사라지면서 비슷한 주제의 새로운 Docs를 골랐습니다.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app

**Comment by justinyoo** [comment]
뉍! 본문 수정했슴다

**Comment by inclue** [comment]
Issue : https://github.com/MicrosoftDocs/azure-docs/issues/60911
PR : https://github.com/MicrosoftDocs/azure-docs/pull/60913

**Comment by inclue** [comment]
Merge 되었습니다
