### ISSUE TITLE
Unit Testing | Unit testing C# with NUnit and .NET Core

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/oss-contributhon-2020-dotnetcore-sdk#9]
* Tracking: #5
* Docs: [Unit testing C# with NUnit and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit?WT.mc_id=osscontributhon-event-juyoo)
* Issue:
* PR:

**Comment by DaeunSim** [comment]
Issue: [#19950](https://github.com/dotnet/docs/issues/19950)
문서에 작성되어 있는 예제 코드에 닫는 괄호가 없어서 이슈 등록하였습니다.
